### PR TITLE
You don't need to make an APP for that.md

### PR DESCRIPTION
**Pull request by tingtingguo**
I accidentally merged my original file.  I think need to create a new one.

### CODE REVIEW

**Comment by tingtingguo** [comment]
@sunmeng0421 @AColker16 @SeanOMealia 

Guys...I'm so confused...Did I do this right?

**Comment by sunmeng0421** [comment]
yes, I can see your essay, let me know if it's finished.

**Comment by tingtingguo** [comment]
@sunmeng0421 yes, I think so

**Comment by tingtingguo** [comment]
But I can't see the merge the pull request?

**Comment by tingtingguo** [comment]
@sunmeng0421 done :) :+1:

**Comment by sunmeng0421** [comment]
@tingtingguo , looks good, :+1:  you need one more to ship!

**Comment by tingtingguo** [comment]
I don't know how I'm going to merge this later...it's telling me we can't automatically merge this pull request? @sunmeng0421

**Comment by tingtingguo** [comment]
@sunmeng0421 @SeanOMealia how do I summon the prof into this thread?  Have a question about merging

**Comment by chendaniely** [comment]
@PeterBell This won't let me merge on github

**Comment by tingtingguo** [comment]
@sunmeng0421 @SeanOMealia got a little help from @chendaniely  i'm good now.   have any comments for me Sean?

**Comment by PeterBell** [comment]
Glad you're set @tingtingguo

**Comment by SeanOMealia** [comment]
@tingtingguo Looks great to me!  The one thing I would do is add a link somewhere in your essay.  @sunmeng0421 showed me this cool site that explains how to insert links. 

https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by tingtingguo** [comment]
thanks for the tip @SeanOMealia 

edit made!  am I good to go?

**Comment by SeanOMealia** [comment]
Looks great!  Well done, @tingtingguo  :+1: 

:sake:  :sake:   :sake:  :sake: :sake:  :sake:  :sake:

**Pull request merged**
