### PR TITLE
Have-an-idea?Now-what?

### PR DESCRIPTION
**Pull request by Clian16**
3rd Try

### CODE REVIEW

**Comment by tingtingguo** [comment]
@Clian16 good start! would recommend making your file a markdown file (add a .md to the end of your file name)  then you can add in some links and other things.

**Comment by tingtingguo** [comment]
@Clian16 can you make the changes suggested? @SeanOMealia Alex is away from the computer today, after Corey makes his changes could you give him a +1.  I will as well so he can ship! Will create a pull request at 12:00.

**Comment by SeanOMealia** [comment]
@Clian16  I like it too!  Could you add a picture and a link?  Both are requested by the assignment prompt.  @tingtingguo I'm heading to West Point in a few minutes and will be away from my computer all day.  I'll try to give a plus 1 from my phone, but am not sure whether that will work.

**Comment by Clian16** [comment]
@tingtingguo @SeanOMealia I updated the text based on Alex's comments and added a link. Changed the file name by adding ".md" to the end but how do I paste in a picture? Pasted in a .jpeg link at the end but it only shows the link and not the picture?

**Comment by tingtingguo** [comment]
Hi @Clian16 check out https://github.com/adam-p/markdown-here/wiki/Markdown-Cheatsheet

**Comment by tingtingguo** [comment]
@Clian16 this looks awesome! :+1:

**Comment by tingtingguo** [comment]
@SeanOMealia @sunmeng0421 can either of you try to give a :+1: ? might work on your phone

**Comment by sunmeng0421** [comment]
:+1

**Comment by sunmeng0421** [comment]
This is good, please merge!

**Comment by Clian16** [comment]
@tingtingguo @sunmeng0421  @SeanOMealia  Just merged!

**Comment by tingtingguo** [comment]
@Clian16 awesome! :) :+1: :+1: :+1: :+1:

**Pull request merged**
