### PR TITLE
Hourly vs Fixed Rate

### PR DESCRIPTION
**Pull request by SeanOMealia**
I found the discussion of hourly versus fixed rate contracts to be very beneficial.  I recommend that we add it to the master. 

Can you give me feedback, @sunmeng0421 @tingtingguo

### CODE REVIEW

**Comment by tingtingguo** [comment]
Hey @SeanOMealia! Great job.  Definitely think your hourly vs fixed article is a nice addition to the lessons-learned file.  Would love to hear about any of your experiences you've had working with developers who preferred either hourly or fixed.

**Comment by tingtingguo** [comment]
@SeanOMealia i created a merge conflict by accident for you...so you can't merge...getting some help to fix it for you! never fear

**Comment by SeanOMealia** [comment]
I made some changes to address @sunmeng0421 and @tingtingguo comments.  Would you two mind giving this a look over and giving me the :+1: if you think it is ready to merge into the master?

**Comment by tingtingguo** [comment]
Yes!! @SeanOMealia  :+1:  

side note to @chendaniely ... can you help me fix that error I made with i did that thing with the master?  sean won't be able to merge :(

**Comment by chendaniely** [comment]
If you rename the file it should fix it.  It's because this branch was originally merged and then @sunmeng0421 deleted the file.  So now when you try to merge it again, github doesn't know which version to keep, the version that was deleted, or the one you are trying to merge in again.

Renaming it will fix it.

**Comment by chendaniely** [comment]
I think what I told @tingtingguo to do was add a `_2` to the end of the file name. so @SeanOMealia you would rename the file form `paying-developers.md` to `paying-developers_2.md` (or something similiar).

Not the best of practices for git/github, but I've been told you can't do any of this on your local computer :p

**Comment by SeanOMealia** [comment]
Thanks a ton @chendaniely!  @peterbell is there a way to rename the branch without losing all of these pull request comments?  I want to make sure the comments carry over so that @tingtingguo and @sunmeng0421 get credit for their comments.

**Comment by tingtingguo** [comment]
@SeanOMealia I think that you can just change it.  It shouldn't change the comments in the thread :)

**Comment by SeanOMealia** [comment]
@tingtingguo do you know how?  I can't figure it out without starting a new branch and a new pull request

**Comment by tingtingguo** [comment]
@SeanOMealia Are you in watson? I can show you!

If you go to edit your file, you should be able to update the name of the file near the top of the page 
screen shot 2015-04-23 at 3 20 53 pm

**Comment by chendaniely** [comment]
In your hourly_software_dev branch you can edit your file.  On the top you can change the file name.  When you go to save make tire the radio button still says to commit to hourly_software_dev. And not master

**Comment by chendaniely** [comment]
Make sure*

Sorry on my phone commuting.

**Comment by tingtingguo** [comment]
@SeanOMealia Fixed it for you :) You're good to go :+1:

**Comment by SeanOMealia** [comment]
Great.  Thanks team.  Merging.

**Pull request merged**
